title: Daniel Leon
logo: assets/img/headshot_circle.png
description: Data Analysis | Statistics | International Development
social:
  - title: "LinkedIn"
    icon: "fab fa-linkedin" # or an emoji
    link: "https://www.linkedin.com/in/daniel-leon-79b50322"
#show_downdloads: true
google_analytics:
theme: jekyll-theme-cayman
#theme: jekyll-theme-minimal
