title: Daniel Leon
logo: assets/img/headshot_circle.png
description: Data Analysis | Statistics | International Development
[LinkedIn](https://www.linkedin.com/in/daniel-leon-79b50322/)
#show_downdloads: true
theme: jekyll-theme-minimal
