title: Daniel Leon
logo: assets/img/headshot_circle.png
description: Data Analysis | Statistics | International Development
platforms:
    name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/daniel-leon-79b50322
#show_downdloads: true
google_analytics:
theme: jekyll-theme-minimalist
